# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K0Dr5ou5k-54U6FKSR-BLg1cJSuaFJO3
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("netflix_titles.csv.zip")
df.head()

df.isnull().sum()

df.fillna("unknown", inplace=True)

df.drop_duplicates(inplace=True)

df['country'] = df['country'].str.lower().str.strip()

df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

df.columns = df.columns.str.lower().str.replace('','_')

df.to_csv("cleaned_netflix.csv", index=False)
files.download("cleaned_netflix.csv")